// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkfkzqxmqxognavlbcng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZmt6cXhtcXhvZ25hdmxiY25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTA2NjQsImV4cCI6MjA1MDYyNjY2NH0.xgQNVifcYKQNHzAwdUR2_zZseDJPQFiH-epPUNKapiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);